### ISSUE TITLE
 Strange visual bug with fireflies (fabric)

### ISSUE THREAD

**Issue by DVIcable** [paulevsGitch/BetterNether#294] opened 2021-01-29 02:17 UTC
Fireflies are only visible with the sky behind them, and have this weird painting effect on the sky
![2021-01-28_19 11 36](https://user-images.githubusercontent.com/76571917/106222579-17ae7100-619d-11eb-92db-a08d6da5c6e1.png)
![2021-01-28_19 11 44](https://user-images.githubusercontent.com/76571917/106222583-18df9e00-619d-11eb-9b22-f6ebe039ab02.png)

It is the only mod installed. (alongside fabric api obviously.)

**Comment by paulevsGitch** [comment] 2021-01-29 07:07
Duplicate of #286, this bug happens only on “fabulous” graphic settings, you can change it to “fancy” and rendering will be fine

**Comment by paulevsGitch** [comment] 2021-06-16 11:20
Fixed in 5.1.0

**Closed by paulevsGitch** 2021-06-16 11:20 UTC
Labels: bug, in dev code, postponed
