### ISSUE TITLE
[Bug] Injection warning

### ISSUE THREAD

**Issue by davidalb97** [paulevsGitch/BetterNether#522] opened 2022-03-09 00:17 UTC
### What happened?

Found an injection warning on the log, is this severe?

Mixin being suppressed:
```
paulevs.betternether.mixin.common.LiquidBlockMixin.bn_shouldSpreadLiquid()
```

### BetterNether

6.0.11

### BCLib

1.3.5

### Fabric API

0.46.6

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Relevant log output

```shell
[main/WARN]: Injection warning: LVT in net/minecraft/class_2404::method_10316(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Z has incompatible changes at opcode 120 in callback betternether.mixins.common.json:LiquidBlockMixin->@Inject::bn_shouldSpreadLiquid(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLcom/google/common/collect/UnmodifiableIterator;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;)V from mod betternether.
 Expected: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;, Lnet/minecraft/class_2248;]
    Found: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
Available: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
```
```


### Other Mods

```shell
None.
```

**Comment by paulevsGitch** [comment] 2022-03-09 00:58
Duplicate of #510

**Closed by paulevsGitch** 2022-03-09 00:58 UTC
Labels: bug
