### ISSUE TITLE
[1.12] Lag with better nether

### ISSUE THREAD

**Issue by arnaullfe** [paulevsGitch/BetterNether#70] opened 2020-04-07 11:35 UTC
My issue with the betterNether is that this mod generate me a lot of lag. But, the lag is when i'm in the world dimension 0, not when i'm in the nether. The reason of the lag is this:

Better Nether::EventsHandler_onWorldSavecount(35)  total(55.33% 7.667s, 383.36% of tick)avg(219.06ms per - 191.68ms/0.88 per tick)

I don't know how solvate this issue, thanks for your help ;)

**Comment by paulevsGitch** [comment] 2020-04-07 17:57
What version do you use?

**Comment by paulevsGitch** [comment] 2020-04-07 18:20
Looks like you use 1.12 (EventsHandler was only in it). So, this is duplicate issue. Disable Nether City generation in the config and all must be fine.

**Comment by paulevsGitch** [comment] 2020-04-07 18:22
Duplicate of #50

**Closed by paulevsGitch** 2020-04-07 18:22 UTC
Labels: bug
