### ISSUE TITLE
Crash when going to nether

### ISSUE THREAD

**Issue by RaoqTheWiz** [paulevsGitch/BetterNether#199] opened 2020-10-13 23:54 UTC
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2020-10-13 16:53:29 MST
Description: Exception generating new chunk

java.lang.ClassCastException: net.minecraft.class_3233 cannot be cast to net.minecraft.class_1937
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at net.Shad0w.Allure.Blocks.Speleothem.SpeleothemBlock.canPlaceAt(SpeleothemBlock.java:49)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.canPlaceAt(AbstractBlock:926)
    at paulevs.betternether.world.BNWorldGenerator.fixBlocks(BNWorldGenerator.java:496)
    at paulevs.betternether.world.BNWorldGenerator.cleaningPass(BNWorldGenerator.java:441)
    at net.minecraft.world.gen.chunk.ChunkGenerator.handler$bgp000$customPopulate(ChunkGenerator:560)
    at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator)
    at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89)
    at net.minecraft.class_2806$$Lambda$2015/1566411942.doWork(Unknown Source)
    at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
    at net.minecraft.class_3898$$Lambda$6726/1375746947.apply(Unknown Source)
    at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
    at net.minecraft.class_3898$$Lambda$6723/984351697.apply(Unknown Source)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
    at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
    at net.minecraft.class_3900$$Lambda$6530/273550505.run(Unknown Source)
    at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
    at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
    at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Chunk to be generated --
  Location: 7,-8
  Position hash: -34359738361
  Generator: net.minecraft.class_3754@48a213c

-- Affected level --
  All players: 1 total; [class_3222['RaoqRocks'/163, l='ServerLevel[Mods Test]', x=19.89, y=86.02, z=-46.01]]
  Chunk stats: ServerChunkCache: 1089
  Level dimension: minecraft:the_nether
  Derived: true
  Level spawn location: World: (144,63,46), Chunk: (at 0,3,14 in 9,2; contains blocks 144,0,32 to 159,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 39595 game time, 39595 day time
  Level name: Mods Test
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
  Level weather: Rain time: 46085 (now: false), thunder time: 2174 (now: true)
  Known server brands: fabric
  Level was modded: true
  Level storage version: 0x04ABD - Anvil

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 437231144 bytes (416 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
  CPUs: 8
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Allure (allure), Better Nether (betternether)
  Fabric Mods: adapaxels: AdaPaxels 1.0.2
               adorn: Adorn *
               advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
               adventurez: AdventureZ 1.1.2
               allure: Allure 1.2.7
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.2.2
               backslot: BackSlot 1.1.5
               backslotaddon: BackSlot Addon 1.0.2
               bag_of_feathers: Bag of Feathers 1.0.0
               beaconsforall: Beacons For All 1.3.0-1.16.3
               better_mod_button: Better Mod Button 1.1.4
               bettercaves: YUNG's Better Caves 1.16.2-1.0.2
               betternether: Better Nether 4.1.3
               biomemakeover: Biome Makeover 1.16.3-1.0.0
               blackstonetools: Blackstone Tools 1.2.0+1.16.1
               blue_endless_jankson: jankson +
               boostedbrightness: Boosted Brightness 1.1.0
               bowinfinityfix: Bow Infinity Fix rv9
               camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.4+MC1.16.2-1.16.3
               cardinal-components: Cardinal Components API 2.6.0
               cardinal-components-base: Cardinal Components API (base) 2.6.0
               cardinal-components-block: Cardinal Components API (blocks) 2.6.0
               cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
               cardinal-components-entity: Cardinal Components API (entities) 2.6.0
               cardinal-components-item: Cardinal Components API (items) 2.6.0
               cardinal-components-level: Cardinal Components API (world saves) 2.6.0
               cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.6.0
               cardinal-components-util: Cardinal Components API (utilities) 2.6.0
               cardinal-components-world: Cardinal Components API (worlds) 2.6.0
               cheatless: Cheatless 0.1.0
               chestcavity: Chest Cavity 1.3.1
               cleancut: CleanCut mc1.16-2.1-fabric
               cleanview: CleanView 1.16.3-v1-fabric
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.2
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
               compactstatuseffects: Compact Status Effects 1.2.2
               controlling: Controlling For Fabric 1.1.2
               craftable_god_apple: Craftable God Apple 1.0.0
               craftingpad: Crafting Pad 1.16.2-fabric0.17.2-1.0.5
               disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
               doublejump: Double Jump Mod 1.16.1-1.0.0
               dynamicfps: Dynamic FPS 1.2.1
               eatanddrink: Eat And Drink 1.1.0
               edit_sign: Edit Sign 2.1.1
               eldritch_mobs: Eldritch Mobs 1.5.1
               enchantablehorsearmor: Enchantable Horse Armor *
               enderitemod: Enderite Mod 1.2.2
               endfestation: Endfestation 1.0.1
               enhancedcraft: EnhancedCraft beta-1.3.1
               eternaleats: Eternal Eats 1.0.2
               fabric: Fabric API 0.24.0+build.411-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
               fabric_armor: Fabric Armor 1.2.1
               fabricloader: Fabric Loader 0.9.3+build.207
               fabricshieldlib: Fabric Shield Lib 1.1.0
               fiber: fiber 0.23.0-1
               fishonaleash: Fish on a Leash! 1.16.3-1.0.0
               glassdoor: Glass Doors 1.5.0-1.16
               glassential: Glassential *
               gottaclimbfast: Gotta Climb Fast! 1.0
               haema: Haema 1.2.2
               houraielixir: Hourai Elixir 1.16.3-1
               howlingwolves: Howling Wolves 1.0.0+build.1
               impersonate: Impersonate 2.0.3
               inmis: Inmis 1.3.0-1.16.2
               intotheomega: Into the Omega 1.1.2-beta-1.16.2
               irishwolves: Irish Wolves 1.0.0
               itemmodelfix: Item Model Fix 0.2.4
               jankson: Jankson 3.0.1+j1.2.0
               karam: Karam 1.2.1
               kyrptconfig: Kytpt Config 1.1.2-1.16
               launchersmod: Launchers 2.1.4
               leaf-decay: Leaf Decay *
               libblockattributes: LibBlockAttributes 0.8.0-pre.18
               libblockattributes_core: LibBlockAttributes (Core) 0.8.0-pre.18
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.0-pre.18
               libblockattributes_items: LibBlockAttributes (Items) 0.8.0-pre.18
               libcd: LibCapableData 3.0.2+1.16.2
               libgui: LibGui 3.0.0+1.16.3
               libstructure: LibStructure 1.5
               lithium: Lithium 0.5.6
               loadcatcher: Entrypoint Catcher 2.0.0
               magic_mirror: Magic Mirror 1.0.2
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               mcg: MCG 1.1.1
               minecraft: Minecraft 1.16.3
               mjmod: Daggers 1.0.0
               mo_glass: Mo Glass 1.4-MC1.16.3
               modify-drops-api: Modify Drops API 0.3.1
               modmenu: Mod Menu 1.14.6+build.31
               moenchantments: Mo'Enchantments 1.13.7
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
               moretotems: More Totems 2.7.0
               moundertweaks: MounderTweaks 1.4.1
               mythicmetals: Mythic Metals 0.8.0
               narratoroff: narrator off 0.0.1
               nbtcrafting: NBT Crafting 2.0.0+mc1.16.2-pre1
               net_gudenau_lib_unsafe: unsafe 1.2.14
               netherite_plus: Netherite Plus Mod 1.0.0
               netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.2
               nogizmo: No Debug Gizmo 1.3
               nomadbooks: Nomad Books 0.5.7
               nostrip: No Strip 1.1.0-1.16.2+
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               notrample: No Trample 0.0.2
               obeyhorses: Obey Horses 1.1
               org_aeonbits_owner_owner: owner 1.0.12
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               overpowered_mending: Overpowered Mending 2.2.2
               parchment: Parchment 1.0.2+1.15.2
               patchouli: Patchouli 1.16-40-FABRIC
               petowner: Pet Owner 1.16.2+-1.6.1
               phosphor: Phosphor 0.6.0+build.7
               photoallergiccreepers: Photoallergic Creepers *
               plantinajar: Plant In A Jar 1.7.2
               projectsavethepets: Project: Save the Pets! 1.0.1+minecraft-1.16.3
               prone: prone 0.1.2
               quickshulker: Quick Shulker 1.1.8-1.16
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               repairableanvils: Repairable Anvils 0.0.2
               repurposed_structures: Repurposed Structures 1.16.3-1.6.7
               rings: Rings 1.1
               rottenflesh2leather: Rotten Flesh To Leather [FABRIC] 1.0.0
               roughlyenoughitems: Roughly Enough Items 5.6.1
               roughlyenoughitems-api: REI (API) 5.6.1
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.6.1
               roughlyenoughitems-runtime: REI (Runtime) 5.6.1
               satin: Satin 1.4.1
               secretrooms: Secret Rooms *
               shulkerboxtooltip: Shulker Box Tooltip 2.3.1+1.16.3
               shulkularity: Shulkularity 1.0.0
               sizeentityattributes: Size Entity Attributes 3
               skinshine: Skin Shine 1.1.5
               slightlyvanilla: SlightlyVanilla 1.0.10+1.16.2
               sodium: Sodium 0.1.0
               soulsoilfarmland: Soul Soil Farmland 0.0.2
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               statushud: StatusHud 1.1.0
               tillitbreaks: Till it Breaks 0.1
               tinytweaks: TinyTweaks 1.0.13
               tool_action_helper: Tool Action Helper 1.0.1
               tooltipfix: ToolTip Fix 1.0.1-1.16
               torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
               trinkets: Trinkets 2.6.5
               uncraftable: Uncraftables *
               unearthed: Unearthed 1.0.3
               unforgivingvoid: Unforgiving Void 2.0.0
               universalcomponents: Universal Components 0.7.3+1.16.2
               vanillaenhanced: VanillaEnhanced 1.3.0
               vanillaexperience: Vanilla Experience 0.2.2
               voyager: Voyager 1.0.0
               walljump: Wall-Jump! 1.3.3+1.16.1
               waystones: Waystones 1.0.6
               wendigoism: Wendigoism 1.16.3-1
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               worldedit: WorldEdit 7.2.0-rc-01+81f978e
  Patchouli open book context: n/a
  Player Count: 1 / 8; [class_3222['RaoqRocks'/163, l='ServerLevel[Mods Test]', x=19.89, y=86.02, z=-46.01]]
  Data Packs: vanilla (incompatible), fabric/trinkets, fabric/adventurez, fabric/chestcavity, fabric/mo_glass, fabric/rings, fabric/morecraftingtables, fabric/moretotems, fabric/repurposed_structures, fabric/launchersmod, fabric/enderitemod (incompatible), fabric/adorn, fabric/vanillaenhanced, fabric/craftable_god_apple, fabric/mjmod, fabric/tinytweaks, fabric/netheritehorsearmor, fabric/wolveswitharmor, fabric/intotheomega, fabric/bag_of_feathers, fabric/haema, fabric/soulsoilfarmland, fabric/inmis, fabric/magic_mirror, fabric/mythicmetals, fabric/endfestation, fabric/enhancedcraft, fabric/adapaxels, fabric/craftingpad, fabric/karam, fabric/glassential, fabric/eldritch_mobs, fabric/blackstonetools, fabric/fabric_armor, fabric/wendigoism, fabric/netherite_plus, fabric/fabric-tool-attribute-api-v1, fabric/unearthed, fabric/libcd, fabric/biomemakeover, fabric/allure, fabric/slightlyvanilla, fabric/waystones, fabric/plantinajar, fabric/uncraftable, fabric/glassdoor, fabric/vanillaexperience (incompatible), fabric/rottenflesh2leather, fabric/secretrooms, secretrooms:server_pack, fabric/nomadbooks, fabric/betternether
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by paulevsGitch** [comment] 2020-10-14 08:03
Duplicate of #169 (solution)

**Closed by paulevsGitch** 2020-10-14 08:03 UTC
