### ISSUE TITLE
[1.17.1] BetterNether and Incendium compatibility solution

### ISSUE THREAD

**Issue by ShinryuAspect** [paulevsGitch/BetterNether#406] opened 2021-08-26 14:22 UTC
So, I was tinkering with both this mod and the Incendium datapack and I couldn't make it so that BetterNether biomes spawned in the nether, I was always getting the generator from Incendium's datapack. To be fair, going into the level.dat and editing the type for the biome_source didn't do anything, so I decided to have a look at the datapack itself and came up with a solution.
For this two things to work together, you have to go into the datapack (the .zip file) and navigate to data/minecraft/dimensions. Once there, just open the "the_nether.json" file with any file explorer (I use SublimeText) and scroll all the way to the bottom. You'll want to replace the line "settings": "starmute:nether3" by "settings": "minecraft:nether" and the line "type": "minecraft:noise" by "type": "betternether:nether_biome_source" (to me, those lines were 299 and 296).
Once you've done this, just save the file and go into the Nether, you'll be able to find both pack's biomes (you can try this by using the _locatebiome_ command and searching for entries from **betternether:** or **starmute:** (just make sure the ones from starmute: are nether ones (for example: basalt_deltas_cooled or something like that), if you happen to have any other pack done by him, such as Terralith).
I manage to make this work, so if anyone reading this tries it and can't make it work, just write over here and I'll try to answer asap.

**Comment by quiqueck** [comment] 2021-11-03 22:36
This should be fixed in 5.3.5 which is based on the new BCLib. Please reopen the issue if the problem is still present.

**Closed by quiqueck** 2021-11-03 22:36 UTC
