### ISSUE TITLE
Map's pointer isn't updating correctly

### ISSUE THREAD

**Issue by Laifsyn** [paulevsGitch/BetterNether#516] opened 2022-02-25 07:50 UTC
### What happened?

Any empty map that's sketched on, the player's pointer won't update correctly. But you can still update the map terrain, is just that you can't see that white dot updating it's orientation neither position. I've tested without Better end installed too. and with only the 2 dependencies + better end

### BetterNether

6.0.10

### BCLib

1.3.4

### Fabric API

0.46.4

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Other Mods

```shell
better-end-1.0.2
```

**Comment by Laifsyn** [comment] 2022-02-25 07:51
Both in the end and overworld, the player pointers updates correctly and no visible issues are found

**Comment by quiqueck** [comment] 2022-02-25 09:15
duplicate of #412

**Closed** 2022-02-25 09:15 UTC
Labels: bug
