### ISSUE TITLE
Ink Bushes Have no Block Tag (1.12)

### ISSUE THREAD

**Issue by Crazydude323** [paulevsGitch/BetterNether#78] opened 2020-04-15 04:45 UTC
Preface: I am in 1.12, which the main page says you are no longer updating. I'm submitting this report in the hope that you still fix bugs for that version, at least.

Ink Bushes have no Block Tag. In other words, they don't show up in JEI, and WAILA also doesn't show anything when you look at them. So you can't Whitelist or Blacklist them, which makes it very difficult to automate them. This is for the full grown bush of course; the seeds work just fine.

**Comment by paulevsGitch** [comment] 2020-04-15 12:30
Ink bushes don’t have an item, and they will not be shown in JEI, this is not bug. I don’t know what you mean under “block tag”,  I hear this term for the first time. The only item they drop is seeds, use them instead.
This is not a bug so I close this issue.

**Closed by paulevsGitch** 2020-04-15 12:30 UTC
