### ISSUE TITLE
le funnie anvil crash

### ISSUE THREAD

**Issue by Redd56** [paulevsGitch/BetterNether#529] opened 2022-03-24 08:18 UTC
### What happened?

Opening an anvil crashes the game.

### BetterNether

6.1.0

### BCLib

1.4.0

### Fabric API

0.48.0

### Fabric Loader

0.13.3

### Minecraft

1.18.2

### Relevant log output

[Crash Report](https://pastebin.com/Dum0hd1U)

**Comment by begriefed** [comment] 2022-03-29 00:49
Same for me.  I was about to start with only bclib and better nether and start adding mods one by one until I found the conflicting ones, but I decided to check here, first.

---

Description: Unexpected error

java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at net.minecraft.screen.AnvilScreenHandler.handler$zff000$be_updateOutput(AnvilScreenHandler:653)
	at net.minecraft.screen.AnvilScreenHandler.updateResult(AnvilScreenHandler)
	at net.minecraft.screen.ForgingScreenHandler.onContentChanged(ForgingScreenHandler:80)
	at net.minecraft.class_4861$1.markDirty(class_4861.java:26)
	at net.minecraft.inventory.SimpleInventory.redirect$bii000$fabric_redirectMarkDirty(SimpleInventory:538)
	at net.minecraft.inventory.SimpleInventory.setStack(SimpleInventory:140)
	at net.minecraft.screen.slot.Slot.setStack(Slot:61)
	at net.minecraft.screen.ScreenHandler.updateSlotStacks(ScreenHandler:594)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onInventory(ClientPlayNetworkHandler:1054)
	at net.minecraft.network.packet.s2c.play.InventoryS2CPacket.apply(InventoryS2CPacket:44)
	at net.minecraft.network.packet.s2c.play.InventoryS2CPacket.apply(InventoryS2CPacket:11)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1085)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:recipe_type / bclib:smithing])
	at net.minecraft.util.registry.SimpleRegistry.assertNotFrozen(SimpleRegistry:80)
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:90)
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:86)
	at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry:134)
	at net.minecraft.util.registry.Registry.register(Registry:471)
	at net.minecraft.util.registry.Registry.register(Registry:467)
	at ru.bclib.recipes.BCLRecipeManager.registerType(BCLRecipeManager.java:63)
	at ru.bclib.recipes.AnvilRecipe.<clinit>(AnvilRecipe.java:41)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1706.handler$zff000$be_updateOutput(class_1706.java:653)
	at net.minecraft.class_1706.method_24928(class_1706.java)
	at net.minecraft.class_4861.method_7609(class_4861.java:80)
	at net.minecraft.class_4861$1.method_5431(class_4861.java:26)
	at net.minecraft.class_1277.redirect$bii000$fabric_redirectMarkDirty(class_1277.java:538)
	at net.minecraft.class_1277.method_5447(class_1277.java:140)
	at net.minecraft.class_1735.method_7673(class_1735.java:61)
	at net.minecraft.class_1703.method_7610(class_1703.java:594)
	at net.minecraft.class_634.method_11153(class_634.java:1054)
	at net.minecraft.class_2649.method_11439(class_2649.java:44)
	at net.minecraft.class_2649.method_11054(class_2649.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)

**Comment by paulevsGitch** [comment] 2022-03-29 07:02
Duplicate of https://github.com/paulevsGitch/BCLib/issues/116

**Closed by paulevsGitch** 2022-03-29 07:02 UTC
Labels: bug
