### ISSUE TITLE
Large Numbers of Mob Spawning

### ISSUE THREAD

**Issue by Mandalorian007** [paulevsGitch/BetterNether#438] opened 2021-11-06 04:23 UTC
I am running a Fabric server with BetterNether installed and I am noticing that large slow downs in ticks can be caused from the Hydrogen Jellyfish and the Flying Pigs.

Tick breakdown:
![tick time overview](https://user-images.githubusercontent.com/3373692/140597662-927c754e-4885-4bba-af80-8d87c8dd0188.PNG)

Tick entity breakdown:
![pig and jellyfish expensive](https://user-images.githubusercontent.com/3373692/140597676-959e4bee-ea83-4031-86e4-7f9c080d3443.PNG)

3 players online during kill commands (1 in nether):
![image](https://user-images.githubusercontent.com/3373692/140597700-0654af4c-a41f-4d40-9b92-5d928ebcf2b9.png)
First kill is pigs and second is jellyfish.

There seem to be extremely large numbers of both of these types of mobs spawning. I am not sure if this is intended as they seem to ignore the mob cap and reach extremely high counts.

**Comment by Mandalorian007** [comment] 2021-11-06 04:26
Current Versions:
bclib 0.3.1
better nether 5.1.3

**Comment by quiqueck** [comment] 2021-11-06 11:45
Thanks for reporting, I'll have a look.

Oddly enough I don't get any to spawn in the latest version...

**Comment by Mandalorian007** [comment] 2021-11-06 13:42
I have noticed that I get no skulls or fireflies on my server. I don't quite understand mob mechanics enough at this point to begin to even speculate what might be occuring

**Comment by quiqueck** [comment] 2021-11-10 07:39
The entity spawning in BN should be fixed, it will probably not address your original issue. I only tested this in a singleplayer world so far, but could not reproduce that high count. It seems to cap at 15 Entities (which it is supposed to).

Will do some more testing in a Multiplayer world later this week.

**Comment by Mandalorian007** [comment] 2021-11-10 16:14
Thank you for that update. Hopefully, we can track this down. Usually, this overspawning mechanic is the main source of tps drops in the world. I should be updating to the latest BN soon, but working on some complexity around the lithium upgrade first. After I get that done I should be able to confirm if this is still in the latest version

**Comment by quiqueck** [comment] 2021-11-30 12:22
The next release (5.3.12) will include our spawning fixes

**Comment by Mandalorian007** [comment] 2021-11-30 13:19
@quiqueck Thank you for tracking down and taking care of this. I had no idea where to even start for this issue and it is greatly appreciated that you were able to track it down and patch it. Thank you on behalf of all the folks on my server <3

**Comment by paulevsGitch** [comment] 2021-12-06 08:29
This was fixed in new releases

**Closed by paulevsGitch** 2021-12-06 08:29 UTC
