### ISSUE TITLE
[1.16.5] Config for items messing up fabric:pickaxes tag

### ISSUE THREAD

**Issue by panbanann** [paulevsGitch/BetterNether#413] opened 2021-09-09 00:09 UTC
Hello,
I was testing the other mod called Gobbers and I first blamed them for the issue. Their mod using some other way of handling tools or something like that and We were not able to mine the blocks that they are adding with any sort of pickaxe.
I contacted them they explain that some other mod messing up fabric tags as they are using `fabric:pickaxes` so I checked out and it happened that the issue is happening if I disable in better nether config either ruby or a cincin-diamond pickaxe.
It is a bit weird but maybe there is something that can be done with it for 1.16.5?
mod version: 5.0.7

**Comment by paulevsGitch** [comment] 2021-09-09 01:40
Hi, if you disable any block/item that was also added into json tags - MC behaviour will be unpredictable, as there are no any checks in MC code if tag content exist or not. Instead of disabling content its better to disable its recipes. This issue is duplicate of #244

**Closed by paulevsGitch** 2021-09-09 01:40 UTC

**Comment by kwpugh** [comment] 2021-09-27 12:13
Hi, MC code does have check for this.  You can use

{
  "replace": false,
  "values": [
  {
    "id": "betternether:betternether",
    "required": false
  },
  {
    "id": "betternether:nether_ruby_pickaxe",
    "required": false
  }
  ]
}

the required=false allows MC to skip over the entry if it was not registered and continue reading  the data.  This is especially true for very common tags like the fabric pickaxes.json.

**Comment by paulevsGitch** [comment] 2021-09-27 13:27
Hi, please use actual issue instead of closed duplicate for the next time

**Comment by kwpugh** [comment] 2021-09-27 13:39
Sorry, sure, will do.
