### ISSUE TITLE
[Suggestion] Nether Boss

### ISSUE THREAD

**Issue by 2Naato** [paulevsGitch/BetterNether#120] opened 2020-06-24 17:57 UTC
I'm sorry if I accidentaly opened a blank issue, I accidentaly pressed enter. Anyway, I'm reposting it here:

**Since Mojang 1.16 update didn't came with a new boss, you have the possibility to make one yourself!**
I really think that there should be one, and _beating it should be the grand final of a nether playthrough_.

If you need any ideas, I already though of:

- **Piglin Chief** (of course): It would spawn inside of one of your amazing nether cities (or bastions, btw I don't know if it's already the case or not but the cities should be dynamicaly populated by piglins).

- Lazy but nonetheless great option: **making the wither only spawnable in the nether** (like the mod nether bound for 1.12, with config of course). 

- **Ghast Queen** : copying nether ex lmao, why not it was a good idea.

- **Lava Kraken**: Would be great, because those large lava lakes need more attention :). In fact I always visualized some sort of big titan emerging from the lava.

Oh, and because I don't like the idea of minecraft having no final boss (the wither and the ender dragon are quite separated and independant in fact), if you decide to make a boss, **it would be cool if it was necessary to beat it before the ender dragon or another final boss**.

Well, this brings me to the second subject: **Better End**.
I know that you are probably planning to make it one day or another (when better nether is completed), but damn it would be SO great. 
Better Nether is an **AMAZING** mod, one of the best gen 3 mod out there. If someday there was a better end of this quality, minecraft would be honestly at a level of greatness beyond science (btw let's pray for an end update in 1.17, this is more needed than a cave update in my opinion).

I think that's all, and thank you for your amazing work on this project!!
(I just felt like I needed to write down a few propositions :) )

**Comment by paulevsGitch** [comment] 2020-06-24 18:11
Duplicate of my comment here: Thank you for your suggestions. I will probably add some bosses like this later, at this moment I'm more concentrated on regular mobs to bring life to the Nether

**Comment by 2Naato** [comment] 2020-06-24 18:18
Thanks for the quick reply (you're truly amazing for working at that impressive speed and bringing us such good content), now you got some more ideas if you need a burst of inspiration!

**Comment by quiqueck** [comment] 2022-01-21 12:05
Moving to our Enhancement List.

**Closed by quiqueck** 2022-01-21 12:05 UTC
Labels: suggestion
