### ISSUE TITLE
Cant get nether ruby with diamond pick?

### ISSUE THREAD

**Issue by SavTac13** [paulevsGitch/BetterNether#546] opened 2022-05-04 22:03 UTC
### What happened?

 When mining ruby in the nether with a diamond pick, enchanted or not, it gives me the xp but doesnt drop any ruby. Any Know how to fix this?

### BetterNether

1.18.1

### BCLib

1.18.1

### Minecraft

1.18.1

**Comment by Redd56** [comment] 2022-05-05 18:28
also in 1.18.2 its that for some reason its set to netherite mining level

**Comment by quiqueck** [comment] 2022-05-09 20:00
That is actually by design. Ruby gear partially outperforms netherite gear now. In order to counter balance this, we increased the mining level.

**Comment by FluffyBumblee** [comment] 2022-05-19 16:37
> That is actually by design. Ruby gear partially outperforms netherite gear now. In order to counter balance this, we increased the mining level.

Could this be replaced with a custom mining level as having it just drop only when a netherite pickaxe is used causes some compat issues.

**Comment by quiqueck** [comment] 2022-05-19 17:21
We are sure open to a change. What kind of compat issue are you refering to?

**Comment by FluffyBumblee** [comment] 2022-05-20 03:17
As in, excavated variants block drops can't scan for custom loot tables. This is being fixed on their end but the issue of the custom loot table still persists. The block should have an extension of 'real' mining levels like tinkers construct does.

**Comment by FluffyBumblee** [comment] 2022-05-20 03:18
So a wooden pickaxe won't mine that block quickly.

**Comment by FluffyBumblee** [comment] 2022-05-20 03:19
And another compat issue is if somebody has the mod 'can I mine this block?', it'll look like it's minable when it isn't because it doesn't have it's own mining level.

**Comment by frankbauer** [comment] 2022-05-20 08:12
Thank you for the Details. This gives me something to test against and fix the issue.

**Comment by quiqueck** [comment] 2022-05-20 08:13
Thank you for the Details. This gives me something to test against and fix the issue.

**Comment by FluffyBumblee** [comment] 2022-05-20 11:19
> Thank you for the Details. This gives me something to test against and fix the issue.

No problem! Thank you for hearing out my suggestion.

**Comment by aumpandya1135** [comment] 2022-06-01 19:46
Where do you find Nether Ruby

**Comment by paulevsGitch** [comment] 2022-06-01 20:39
All Nether ores don't have specific level or biome to spawn in

**Closed** 2022-06-08 09:43 UTC
Labels: enhancement
