### ISSUE TITLE
[1.16.3] Error when generating terrain ResourceKey[minecraft:dimension / minecraft:the_nether] -15 32

### ISSUE THREAD

**Issue by ProsperCraft** [paulevsGitch/BetterNether#220] opened 2020-11-05 05:56 UTC
Stacktrace in server console when player is in the nether-
https://gist.github.com/ProsperCraft/6b2a923c92231c28330ba3142d408807

Server log-
https://gist.github.com/ProsperCraft/c840efb8f199030e80c997814b1b810c

better-nether-4.1.8.jar
fabric-1.16.1-geckolib-2.0.0

**Comment by paulevsGitch** [comment] 2020-11-05 09:09
This is bug with Allure mod, duplicate of #169 issue. You can disable terrain_cleaning_pass and world_fixing_pass to fix that

**Closed by paulevsGitch** 2020-11-05 09:09 UTC
