### ISSUE TITLE
BetterNether interfere the WorldGen of Age of Exile.

### ISSUE THREAD

**Issue by DaisukeVN** [paulevsGitch/BetterNether#346] opened 2021-05-09 19:17 UTC
Hey.

Problem:
Your Mod interfere the WorldGen of Age of Exile.
After Entering a Dimension of Age of Exile. My Server crash because of "NoChunk"-Error through "BetterNether"

Error:
https://pastebin.com/FBKtRDYp

Can you please proof it and fix? Thank you

**Comment by paulevsGitch** [comment] 2021-05-13 18:16
Looks like generator asks for non-existing chunk, I actually don't know why (as this event works only with existed chunks), probably something interrupt chunk generation, so this looks like mod conflict. At this time it is not possible to fix it as all generator is relative to populator, it will be auto-fixed when whole generation system will be redone after refactoring

**Comment by paulevsGitch** [comment] 2021-06-16 10:48
The issue is similar to #358, additional check should fix it

**Comment by paulevsGitch** [comment] 2021-06-16 11:19
Fixed in 5.1.0

**Closed by paulevsGitch** 2021-06-16 11:19 UTC
Labels: bug, compatibility, in dev code, postponed
