### ISSUE TITLE
[Bug] Crash (Biome decoration)

### ISSUE THREAD

**Issue by MJRamon** [paulevsGitch/BetterNether#472] opened 2021-12-19 00:08 UTC
### What happened?

Game crashed while exploring.

### BetterNether

better-nether-6.0.6

### BCLib

bclib-1.1.2

### Fabric API

fabric-api-0.44.0+1.18

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
https://pastebin.com/WJmTfE2W
```

**Comment by LilyLicht** [comment] 2021-12-19 14:52
Confirmed, same bug here.

**Comment by Excali2** [comment] 2021-12-19 19:00
Me too, same bug, it crashes the game when you try to enter the nether

**Comment by ChrisClark13** [comment] 2021-12-19 20:43
Same bug here.

Surprisingly, I was able to get the Better Nether generation to work initially by using the Origins mod to spawn me in there.

But when I entered and exited the game I got this crash.

https://crashy.net/QzTx6FuBmgfKcFGpCqiF

https://crashy.net/6oKFiri1U3etfQ9JBGOc

**Comment by quiqueck** [comment] 2021-12-19 22:03
Just for the record, do you use any mod that disables the experimental world warning? If so, the latest update to BCLib (1.1.3) fixes this crash.

**Comment by quiqueck** [comment] 2021-12-19 22:14
duplicate of #468

**Comment by ChrisClark13** [comment] 2021-12-19 23:06
Updating BCLib to 1.3 fixed it for me, though oddly the latest version doesn't show up in the CurseForge Client just yet.

Now to regenerate the nether and explore your mod!

**Comment by Excali2** [comment] 2021-12-20 08:00
> Just to make sure this is the same issue: do you use any mod that disables the experimental world warning? If so, the latest update to BCLib (1.1.3) fixes this crash.

This work for me too

**Comment by quiqueck** [comment] 2021-12-20 09:41
Thanks for reporting back. I‘ll close this for now then.

**Closed by quiqueck** 2021-12-20 09:41 UTC
Labels: bug, question
