### ISSUE TITLE
[Bug] Crash when entering nether

### ISSUE THREAD

**Issue by ssttevee** [paulevsGitch/BetterNether#499] opened 2022-01-18 04:55 UTC
### What happened?

Dedicated server crashes when entering nether.

### BetterNether

6.0.8

### BCLib

1.2.2

### Fabric API

0.45.0+1.18

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
[04:46:52] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'int java.util.Random.nextInt(int, int)'
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'int java.util.Random.nextInt(int, int)'
	at paulevs.betternether.world.structures.plants.StructureHookMushroom.generate(StructureHookMushroom.java:15) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.world.NetherBiome.genCeilObjects(NetherBiome.java:167) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.world.BNWorldGenerator.populate(BNWorldGenerator.java:218) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.world.features.NetherChunkPopulatorFeature.method_13151(NetherChunkPopulatorFeature.java:37) ~[better-nether-6.0.8.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:80) ~[server-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:56) ~[server-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:316) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.md9e41c8$lambda$injectLightmapSetup$1$4(class_2806.java:546) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:605) ~[server-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:599) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
```

### Other Mods

```shell
-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.10.28-Unraid
	Java Version: 17-ea, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 67672936 bytes (64 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1281 v3 @ 3.70GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7989.59
	Virtual memory used (MB): 11609.07
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx2G
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		adventurez: AdventureZ 1.4.7
		ae2: Applied Energistics 2 10.0.0-beta.5
		ae2wtlib: AE2WTLib 10.0.0-beta.5
		agape_space: Space Dimensions 0.4.6
		alloy_forgery: Alloy Forgery 2.0.8+1.18
		amplified_nether: Amplified Nether for Fabric 1.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.5.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.2
		arcanus: Arcanus 1.25
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.4.9
		artifality: Artifality 0.5.2
		attributefix: AttributeFix 13.0.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autosmeltenchant: AutosmeltEnchant 1.1.0
		awesomedungeon: Awesome Dungeon 2.0.3
		backslot: BackSlot 1.2.4
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.4.0+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		basicaiots: Basic AIOTs 1.3.3+1.18.1
		bclib: BCLib 1.2.2
		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.3
		betterend: Better End 1.0.0
		betternether: Better Nether 6.0.8
		bewitchment: Bewitchment 1.18-6
		biome_locator: Biome Locator 1.3.2
		bitsandchisels: BitsAndChisels 2.6.4
		blast: BLAST 1.8.2
		blue_endless_jankson: jankson 1.2.1
		bno: Basic Nether Ores 1.18.1-7.1.1-Fabric
		boatcontainer: BoatContainer 1.0.4
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		bountiful: Bountiful 2.0.1
		bowinfinityfix: Bow Infinity Fix rv11
		camsbackpacks: Cammie's Wearable Backpacks 2.7
		capybara: Capybara 1.0.1
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.0
		chalk: Chalk 1.2.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chunky: Chunky 1.2.164
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-api: Cloth API 3.0.55
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.0.55
		cloth-common-events-v1: Cloth Common Events v1 3.0.55
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 3.0.55
		cloth-utils-v1: Cloth Utils v1 3.0.55
		clumps: Clumps 8.0.4
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_draylar_omega-config: omega-config 1.0.8-1.17
		com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.0-1.18
		complete_bone_meal: Complete Bone Meal 1.3.0
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.18+1.18
		connected-doors: Connected Doors 1.1+1.18
		consistency_plus: Consistency Plus 0.4.3+1.18
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		couplings: Couplings 1.7.1+1.18
		craftingcraft: CraftingCraft 11.0.0
		craftingpad: Crafting Pad 1.0.7
		craftingtweaks: Crafting Tweaks 13.0.0
		crookedcrooks: Crooked Crooks 2.0.1+1.18.1
		croparia: Croparia 0.0.5
		croptopia: Croptopia 1.8.0
		croptosis: Croptosis 1.4.2
		crowdin-translate: CrowdinTranslate 1.4+1.18
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		danceofgrowth: Twerk / Crop Dusting Mod 1.0
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkpaintings: DarkPaintings 9.0.2
		deathlog: DeathLog 0.2.6+1.18
		decorative_blocks: Decorative Blocks 2.0.2
		deepslatecutting: Deepslate Cutting 1.3.0
		diggusmaximus: Diggus Maximus 1.5.2-1.18
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.0-beta2
		dml-refabricated-base: DML: Refabricated - Base 0.5.0-beta2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.0-beta2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.0-beta2
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.0-beta2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.0-beta2
		dragonloot: DragonLoot 1.0.10
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		dynmap: Dynmap 3.3-beta-4
		emerald_tools: Emerald Tools 1.3.33
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		exdel: Explorer's Delight 1.0.0-beta.3+1.18
		expandedstorage: Expanded Storage 7.3.6
		explorerscompass: Explorer's Compass 1.18.1-2.0.2-fabric
		extragenerators: Extra Generators 1.1.1-BETA+1.18
		ezpas: Ezpas 2.0.1
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.0+abf02f7665
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5514
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabric-tree-chopper: Fabric Tree Chopper 0.8.0
		fabricloader: Fabric Loader 0.12.12
		fake-player-api: Fake Player API 0.3.0
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farsight: Farsight Mod 1.18-1.5
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		flesh2leather: Flesh2Leather 1.0.2
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.4
		forgeconfigapiport: Forge Config API Port 3.1.1
		friendsandfoes: Friends&Foes 1.1.2
		geckolib3: Geckolib 3.0.24
		geodes: More Geodes 1.2.0
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.1-1.18.1
		gobber2: Gobber2 2.5.59
		goblintraders: Goblin Traders 1.4.1
		goldenhoppers: Golden Hoppers 1.1.0
		golemsgalore: Golems Galore 1.1.1-1.18
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.1
		grindenchantments: Grind Enchantments 1.5.0+1.18
		guild: Guild 0.3.8
		hologram-api: Hologram API 0.2.1+1.18-pre5
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iceberg: Iceberg 1.0.38
		impaled: Impaled 1.0.2
		impersonate: Impersonate 2.4.0
		incantationem: Incantationem 1.1.3+1.18.1
		indrev: Industrial Revolution 1.13.6-BETA
		inventorysorter: Inventory Sorter 1.8.4-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.1-1.18
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kjsextras: KubeJS Extras 1.5.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.6
		ktdatataglib: KtDataTagLib 1.6.4-1
		kubejs: KubeJS 1801.4.1-build.271
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.3
		lifts: Lifts 1.4-BETA+1.18
		lithium: Lithium 0.7.7
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magna: Magna 1.7.0-1.18-pre1
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18
		mcdict: MCDict 2.1.0+1.17.1
		medievalweapons: Medieval Weapons 1.1.7
		megane: megane 6.2.0
		megane-applied-energistics-2: megane-applied-energistics-2 6.2.0+10.0.0-alpha.1
		megane-base: megane-base 6.2.0
		megane-dml-simulacrum: megane-dml-simulacrum 6.2.0+0.5.0-beta2
		megane-extra-generators: megane-extra-generators 6.2.0+1.1.1-BETA-1.18
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-industrial-revolution: megane-industrial-revolution 6.2.0+1.13.1-BETA
		megane-kibe: megane-kibe 6.2.0+1.9.4-BETA-1.18
		megane-lib-block-attributes: megane-lib-block-attributes 6.2.0+0.10.0
		megane-modern-industrialization: megane-modern-industrialization 6.2.0+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.2.0+5.1.0-beta.2
		megane-runtime: megane-runtime 6.2.0
		megane-team-reborn-energy: megane-team-reborn-energy 6.2.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.2.0+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		mining_dims: Mining Dimensions 1.2.38
		mm: Manningham Mills 2.3
		mob_catcher: Mob Catcher 1.1.20
		modern_industrialization: Modern Industrialization 1.0.4
		more-axolotls: More Axolotls 1.0.2
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		mtmechs: Magitek Mechs 1.0.10
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		myron: Myron 1.6.2+1.18.1
		mythic-mounts: Mythic Mounts 1.18-4.0
		nears: Nears 1.1.2
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.10
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		npcvariety: NPC Variety 2.2.2
		offlineskins: OfflineSkins 1.18.1-v1-fabric
		omega-config: OmegaConfig 1.2.2-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		openloader: OpenLoader 11.0.3
		org_apache_commons_commons-compress: commons-compress 1.19
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_tukaani_xz: xz 1.9
		owo: oωo 0.3.14+1.18
		oxidized: Oxidized 1.5.2
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18.1-64-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		phosphor: Phosphor 0.8.1
		pigsteel: Pigsteel Mod 1.7.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		plushies: Plushie Mod 1.1
		polymer: Polymer 0.2.0-beta.8+1.18
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.8+1.18
		polymorph: Polymorph 0.0.18-1.18.1
		pugh_lib: Pugh Lib 1.2.13
		pugh_tools: Pugh Tools 1.1.16
		puzzleslib: Puzzles Lib 3.1.3
		quarrymod: Industrial Quarry Mod 0.5.4
		quarryplus: QuarryPlus 18.2.0
		quartzelv: Quartz Elevator 2.0.1+1.18
		quickshulker: Quick Shulker 1.3.3-1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.5
		recipeconditions: Fabric Recipe Conditions 0.4.1
		redstonebits: Redstone Bits 1.6.2
		repurposed_structures: Repurposed Structures 3.2.0+1.18.1
		respawnablepets: Respawnable Pets 1.18-1
		rhino: Rhino 1800.1.7-build.92
		rightclickharvest: Right Click Harvest 1.5.1
		ring_of_enderchest: Ring of Enderchest 1.2.18
		ring_of_growth: Ring Of Growth 1.2.18
		ring_of_miner: Ring Of Miner 1.3.18
		ringsofascension: Rings of Ascension 1.0
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.1.361
		roughlyenoughresources: Roughly Enough Resources 2.3.0
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		simple_backpack: SimpleBackpack 1.2.28
		simplegrinder: Simple Grinder 18_1.0.1
		simpleteleporters: Simple Teleporters 2.3.0
		smootherbedrock: Smoother Bedrock 1.0.3
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.4
		stacc: Stacc 1.2.3
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.1
		storagecabinet: Storage Cabinet 1.4.2
		strawdummy: Straw Dummy 1.6.0
		structurized: Structurized 1.4.0+1.18
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.1.0-beta.5
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.8
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		textile_backup: Textile Backup 2.3.0-1.18
		things: Things 0.2.11+1.18
		thonkutil: ThonkUtil 1.3
		timeinabottle: Time in a Bottle 1.6-mc1.17-fabric
		toms_storage: Tom's Simple Storage Mod 1.1.19
		totemmod: Wither Totems Mod 0.3.4-1.18-rc2
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		tradingpost: Trading Post 3.1.2
		trashslot: TrashSlot 11.0.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		twm: The Wild Mod 0.4
		universal-graves: Universal Graves 1.2.2+1.18
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		vanilla_degus: Vanilla Degus 1.3.0
		vanillatweaks: VanillaTweaks 1.5.53
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.2
		voicechat: Simple Voice Chat 1.18.1-2.1.28
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		voidz: VoidZ 1.0.5
		wands: Building Wands 2.3.1
		waterdripsound: Drip Sounds 1.18-0.3.0
		waystones: Waystones 2.4.1
		wolveswitharmor: Wolves With Armor 1.7.0-1.18
		wthit: wthit 4.4.1
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
		xlpackets: XLPackets 2.1-1.17.1
		yosbr: YOSBR 0.1.1
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, Fabric Mods, data/BlazeandCaves Advancements Pack 1.13.1.zip, data/anti enderman grief v1.1.0.zip (incompatible), data/ichphilipp-s-endcity-v1-1-1-16-2.zip (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by quiqueck** [comment] 2022-01-18 09:54
Thanks for reporting, but this is an odd one. `randomNextInt(int, int)` is part of the regular java-API. But I think I can change the our code to use a different one...

**Comment by quiqueck** [comment] 2022-01-19 18:17
New version is released so I'll close this issue for now. If the bug is not resolved for you, then please reopen it.

**Closed by quiqueck** 2022-01-19 18:17 UTC
Labels: bug, in dev code

**Comment by Ghost-chu** [comment] 2022-04-20 16:03
Sorry for comment:
I'm a Bukkit plugin developer and I also get into this trouble about `java.lang.NoSuchMethodError: 'int java.util.Random.nextInt(int, int)'`.

My user tried switch to Java 11 and Java 17 (AdoptOpenJDK) but both same error on Windows Server platform.

But for me Java 17 Adoptmium OpenJDK on Windows 11 cannot reproduce it. THAT'S REALLY STRANGE.

Workaround `Random#nextInt(int)` works, so that's run out of my mind.

I found this issue from a Google, and now I'm pasting as much information as I can here in the hope that others with the same problem will find the answer.
