### ISSUE TITLE
Allure Incompatibility

### ISSUE THREAD

**Issue by thresh1474** [paulevsGitch/BetterNether#221] opened 2020-11-05 06:02 UTC
The Allure mod is not compatible with the current version of better nether, and it is a pretty essential mod for me. If someone could take a look into it that would be great.

**Comment by paulevsGitch** [comment] 2020-11-05 09:06
Duplicate of #169 issue, the problem is on Allure side, but not seems that anyone will fix that. You can disable terrain_cleaning_pass and world_fixing_pass

**Closed by paulevsGitch** 2020-11-05 09:06 UTC
