### ISSUE TITLE
Crash when loading Nether Chunks

### ISSUE THREAD

**Issue by Tanden22** [paulevsGitch/BetterNether#329] opened 2021-03-11 04:35 UTC
Hey,
i was roaming through the nether, and as i walked into a basalt delta (i think) the game locked up. any advice?

https://gist.github.com/Tanden22/8e1135c8e9ec1bc77c8712a81f02f8bf

**Comment by paulevsGitch** [comment] 2021-03-11 10:24
Looks like something forced chunks in the Nether generate in separate threads, and this resulted as Concurrent Modification Exception. I think I can make population lists unique for each chunk, this will solve this issue

**Comment by 3prm3** [comment] 2021-04-11 21:44
1/04/2021 14:42:54 PM] [main/INFO]: Loaded 5254 advancements
[11/04/2021 14:43:11 PM] [main/INFO]: Resizing built chunk storage to 2
[11/04/2021 14:43:11 PM] [main/INFO]: Resizing built chunk storage to 6
[11/04/2021 14:43:12 PM] [main/INFO]: Client Changed Dimension from gobber2:nethering to minecraft:the_nether time: 99044
[11/04/2021 14:43:12 PM] [main/INFO]: Client Teleported VerticalConnectingPortal{296,up,(gobber2:nethering 0 0 0)->(minecraft:the_nether 0 128 0)} 99044
[11/04/2021 14:43:13 PM] [Server thread/INFO]: **MINECRAFTUSERNAME** :: (gobber2:nethering 89.17839233096238 -2.101170889359593 47.32962738060886)->(minecraft:the_nether 89 125 47)
[11/04/2021 14:43:13 PM] [Server thread/INFO]: **MINECRAFTUSERNAME** has made the advancement [We Need to Go Deeper]
[11/04/2021 14:43:13 PM] [main/INFO]: [CHAT] **MINECRAFTUSERNAME** has made the advancement [We Need to Go Deeper]
[11/04/2021 14:43:13 PM] [main/INFO]: Loaded 5278 advancements
[11/04/2021 14:43:15 PM] [Server thread/ERROR]: Encountered an unexpected exception
[11/04/2021 14:43:15 PM] net.minecraft.class_148: Exception generating new chunk
[11/04/2021 14:43:15 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875) ~[intermediary-client-1.16.5.jar:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811) ~[intermediary-client-1.16.5.jar:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.MinecraftServer.handler$ddn000$modifiedRunLoop(MinecraftServer:9810) ~[intermediary-client-1.16.5.jar:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651) ~[intermediary-client-1.16.5.jar:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-client-1.16.5.jar:?]
[11/04/2021 14:43:15 PM] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[11/04/2021 14:43:15 PM] Caused by: java.lang.NullPointerException: No chunk exists at [-4, 0]
[11/04/2021 14:43:15 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.world.ChunkRegion.getBlockState(ChunkRegion:1060) ~[?:?]
[11/04/2021 14:43:15 PM] 	at paulevs.betternether.world.BNWorldGenerator.canReplace(BNWorldGenerator.java:370) ~[better-nether-5.0.7.jar:?]
[11/04/2021 14:43:15 PM] 	at paulevs.betternether.world.BNWorldGenerator.prePopulate(BNWorldGenerator.java:329) ~[better-nether-5.0.7.jar:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$bip000$customPopulate(ChunkGenerator:1033) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.world.chunk.ChunkStatus.md786031$lambda$injectLightmapSetup$1$4(ChunkStatus:1546) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219) ~[?:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568) ~[?:?]
[11/04/2021 14:43:15 PM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[11/04/2021 14:43:15 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562) ~[?:?]
[11/04/2021 14:43:15 PM] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
[11/04/2021 14:43:16 PM] 	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
[11/04/2021 14:43:16 PM] 	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
[11/04/2021 14:43:16 PM] 	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282]
[11/04/2021 14:43:16 PM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282]
[11/04/2021 14:43:17 PM] [Server thread/ERROR]: This crash report has been saved to: **USERSDIR**\instances\VanillaMinecraftWithFabric\crash-reports\crash-2021-04-11_14.43.15-server.txt
[11/04/2021 14:43:17 PM] [Server thread/INFO]: Stopping server
[11/04/2021 14:43:17 PM] [Server thread/INFO]: Saving players
[11/04/2021 14:43:17 PM] [14:43:15] [main/FATAL]: Minecraft ran into a problem! Report saved to: **USERSDIR**\instances\VanillaMinecraftWithFabric\crash-reports\crash-2021-04-11_14.43.15-server.txt
[11/04/2021 14:43:17 PM] ---- Minecraft Crash Report ----
[11/04/2021 14:43:17 PM] // Don't do that.
[11/04/2021 14:43:17 PM] 
[11/04/2021 14:43:17 PM] Time: 4/11/21 2:43 PM
[11/04/2021 14:43:17 PM] Description: Exception generating new chunk
[11/04/2021 14:43:17 PM] 
[11/04/2021 14:43:17 PM] java.lang.NullPointerException: No chunk exists at [-4, 0]
[11/04/2021 14:43:17 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
[11/04/2021 14:43:17 PM] 	at net.minecraft.world.ChunkRegion.getBlockState(ChunkRegion:1060)
[11/04/2021 14:43:17 PM] 	at paulevs.betternether.world.BNWorldGenerator.canReplace(BNWorldGenerator.java:370)
[11/04/2021 14:43:17 PM] 	at paulevs.betternether.world.BNWorldGenerator.prePopulate(BNWorldGenerator.java:329)
[11/04/2021 14:43:17 PM] 	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$bip000$customPopulate(ChunkGenerator:1033)
[11/04/2021 14:43:17 PM] 	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator)
[11/04/2021 14:43:17 PM] 	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89)
[11/04/2021 14:43:17 PM] 	at net.minecraft.world.chunk.ChunkStatus.md786031$lambda$injectLightmapSetup$1$4(ChunkStatus:1546)
[11/04/2021 14:43:17 PM] 	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
[11/04/2021 14:43:17 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
[11/04/2021 14:43:17 PM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[11/04/2021 14:43:17 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
[11/04/2021 14:43:17 PM] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
[11/04/2021 14:43:17 PM] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
[11/04/2021 14:43:17 PM] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
[11/04/2021 14:43:18 PM] 	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
[11/04/2021 14:43:18 PM] 	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
[11/04/2021 14:43:18 PM] 	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
[11/04/2021 14:43:18 PM] 	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[11/04/2021 14:43:18 PM] 
[11/04/2021 14:43:18 PM] 
[11/04/2021 14:43:18 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[11/04/2021 14:43:18 PM] ---------------------------------------------------------------------------------------
[11/04/2021 14:43:18 PM] 
[11/04/2021 14:43:18 PM] -- Chunk to be generated --
[11/04/2021 14:43:18 PM] Details:
[11/04/2021 14:43:18 PM] 	Location: 13,0
[11/04/2021 14:43:18 PM] 	Position hash: 13
[11/04/2021 14:43:18 PM] 	Generator: net.minecraft.class_3754@62fc1d99
[11/04/2021 14:43:18 PM] Stacktrace:
[11/04/2021 14:43:18 PM] 	at net.minecraft.class_3898.method_17225(class_3898.java:573)
[11/04/2021 14:43:18 PM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[11/04/2021 14:43:18 PM] 	at net.minecraft.class_3898.method_17224(class_3898.java:562)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
[11/04/2021 14:43:18 PM] 	at net.minecraft.class_3900.method_17634(class_3900.java:58)
[11/04/2021 14:43:18 PM] 	at net.minecraft.class_3846.method_16907(class_3846.java:94)
[11/04/2021 14:43:18 PM] 	at net.minecraft.class_3846.method_16900(class_3846.java:137)
[11/04/2021 14:43:18 PM] 	at net.minecraft.class_3846.run(class_3846.java:105)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11/04/2021 14:43:18 PM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[11/04/2021 14:43:18 PM] -- Affected level --
[11/04/2021 14:43:18 PM] Details:
[11/04/2021 14:43:18 PM] 	All players: 1 total; [class_3222['**MINECRAFTUSERNAME**'/181, l='ServerWorld minecraft:the_nether 1337', x=85.62, y=121.22, z=47.93]]
[11/04/2021 14:43:18 PM] 	Chunk stats: ServerChunkCache: 1521
[11/04/2021 14:43:18 PM] 	Level dimension: minecraft:the_nether
[11/04/2021 14:43:18 PM] 	Derived: true
[11/04/2021 14:43:18 PM] 	Level spawn location: World: (64,71,240), Chunk: (at 0,4,0 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[11/04/2021 14:43:18 PM] 	Level time: 70629 game time, 70629 day time
[11/04/2021 14:43:18 PM] 	Level name: 1337
[11/04/2021 14:43:18 PM] 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
[11/04/2021 14:43:18 PM] 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[11/04/2021 14:43:18 PM] 	Known server brands: fabric
[11/04/2021 14:43:18 PM] 	Level was modded: true
[11/04/2021 14:43:18 PM] 	Level storage version: 0x04ABD - Anvil
[11/04/2021 14:43:18 PM] -- System Details --
[11/04/2021 14:43:18 PM] Details:
[11/04/2021 14:43:18 PM] 	Minecraft Version: 1.16.5
[11/04/2021 14:43:18 PM] 	Minecraft Version ID: 1.16.5
[11/04/2021 14:43:19 PM] 	Operating System: Windows 10 (amd64) version 10.0
[11/04/2021 14:43:19 PM] 	Java Version: 1.8.0_282, AdoptOpenJDK
[11/04/2021 14:43:19 PM] 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
[11/04/2021 14:43:19 PM] 	Memory: 853026648 bytes (813 MB) / 3556769792 bytes (3392 MB) up to 10737418240 bytes (10240 MB)
[11/04/2021 14:43:19 PM] 	CPUs: 8
[11/04/2021 14:43:19 PM] 	JVM Flags: 13 total; -XX:-OmitStackTraceInFastThrow -Xms1024M -Xmx5632M -XX:MetaspaceSize=640M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=30 -XX:G1ReservePercent=30 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
[11/04/2021 14:43:19 PM] 	Suspected Mods: Better Nether (betternether)
[11/04/2021 14:43:19 PM] 	Fabric Mods: 
[11/04/2021 14:43:19 PM] 		adabraniummod: Adabranium 1.3.2+1.16.5
[11/04/2021 14:43:19 PM] 		adapaxels: AdaPaxels 1.0.6+1.16.5
[11/04/2021 14:43:19 PM] 		addendum: Addendum 1.16.5-1.0.2
[11/04/2021 14:43:19 PM] 		adorn: Adorn 1.13.0+1.16.5
[11/04/2021 14:43:19 PM] 		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
[11/04/2021 14:43:19 PM] 		advancementinfo: AdvancementInfo 1.16.5-fabric0.30.0-1.2
[11/04/2021 14:43:19 PM] 		allure: Allure 1.2.8
[11/04/2021 14:43:19 PM] 		amecs: Amecs 1.3.3+mc.1.16.3
[11/04/2021 14:43:19 PM] 		amecsapi: Amecs API 1.1.3+mc1.16.5
[11/04/2021 14:43:19 PM] 		angerable-patch: Angerable Patch 1.1.0-1.16.4
[11/04/2021 14:43:19 PM] 		architectury: Architectury 1.9.132
[11/04/2021 14:43:19 PM] 		arstheurgia: Ars Theurgia 1.0.6
[11/04/2021 14:43:19 PM] [14:43:15] [Server thread/INFO]: **MINECRAFTUSERNAME** lost connection: Internal Exception: java.lang.StackOverflowError
[11/04/2021 14:43:19 PM] [Server thread/INFO]: **MINECRAFTUSERNAME** left the game
[11/04/2021 14:43:19 PM] [14:43:16] [Worker-Main-600/WARN]: Worker-Main-600 died
[11/04/2021 14:43:19 PM] java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
[11/04/2021 14:43:19 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] [Server thread/INFO]: ThreadedAnvilChunkStorage (1337): All chunks are saved
[11/04/2021 14:43:19 PM] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_nether 1337'/minecraft:the_nether
[11/04/2021 14:43:19 PM] [14:43:18] [Server thread/ERROR]: Exception stopping the server
[11/04/2021 14:43:19 PM] java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
[11/04/2021 14:43:19 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] Caused by: net.minecraft.class_148: Exception generating new chunk
[11/04/2021 14:43:19 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:579) ~[?:?]
[11/04/2021 14:43:19 PM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562) ~[?:?]
[11/04/2021 14:43:19 PM] 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	... 11 more
[11/04/2021 14:43:19 PM] Caused by: java.util.ConcurrentModificationException
[11/04/2021 14:43:19 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
[11/04/2021 14:43:19 PM] 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_282]
[11/04/2021 14:43:19 PM] 	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$bip000$customPopulate(ChunkGenerator:1037) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.world.chunk.ChunkStatus.md786031$lambda$injectLightmapSetup$1$4(ChunkStatus:1546) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219) ~[?:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568) ~[?:?]
[11/04/2021 14:43:19 PM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[11/04/2021 14:43:19 PM] 	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562) ~[?:?]
[11/04/2021 14:43:19 PM] 	... 11 more
[11/04/2021 14:43:19 PM] [main/INFO]: Stopping worker threads
[11/04/2021 14:43:19 PM] [main/INFO]: Stopping worker threads
[11/04/2021 14:43:19 PM] [main/INFO]: Stopping worker threads
[11/04/2021 14:43:19 PM] AL lib: (EE) alc_cleanup: 1 device not closed
[11/04/2021 14:43:23 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[11/04/2021 14:43:23 PM] Checking for updated files!
[11/04/2021 14:43:23 PM] Checking for updates to CurseForge instances

**Comment by paulevsGitch** [comment] 2021-06-16 10:50
This issue will be fixed when BN will be refactored and all features will use MC populators instead of custom generation system

**Closed** 2021-11-16 09:37 UTC
Labels: bug, postponed
